// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://sldrxhkkoykvadgwqmuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZHJ4aGtrb3lrdmFkZ3dxbXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MzY0MjIsImV4cCI6MjA1ODAxMjQyMn0.kdKpmNnAYjCEBqNI3WPPXhQPRP_1d679pbINIc8EChY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);