// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

// Get environment variables with fallback for safety
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://sldrxhkkoykvadgwqmuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsZHJ4aGtrb3lrdmFkZ3dxbXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MzY0MjIsImV4cCI6MjA1ODAxMjQyMn0.kdKpmNnAYjCEBqNI3WPPXhQPRP_1d679pbINIc8EChY";

// Log which values we're using (for debugging)
console.log('Using Supabase URL (integration):', SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);